var laavor_SG1__Dust_Bugs_;var laavor_SG1__Energy_beings_;var laavor_SG1__Furlings_;var laavor_SG1__Gadmeer_;String.prototype.res_is_42=function(){"use strict";var _7_7_=parseInt(this);return _7_7_;};function LaavorAccordion(favatavav_1,aeadaewdaewww_2){if(laavor_SG1__Energy_beings_===undefined||laavor_SG1__Energy_beings_===null)
{laavor_SG1__Energy_beings_=[];}
if(laavor_SG1__Dust_Bugs_===undefined||laavor_SG1__Dust_Bugs_===null)
{laavor_SG1__Dust_Bugs_=[];}
if(laavor_SG1__Furlings_===undefined||laavor_SG1__Furlings_===null)
{laavor_SG1__Furlings_=[];}
laavor_SG1__Furlings_.push(favatavav_1);if(laavor_SG1__Gadmeer_===undefined||laavor_SG1__Gadmeer_===null)
{laavor_SG1__Gadmeer_=[];}
if(aeadaewdaewww_2!==undefined&&aeadaewdaewww_2!==null){laavor_SG1__Gadmeer_[favatavav_1]=aeadaewdaewww_2;}
else{laavor_SG1__Gadmeer_[favatavav_1]=laavor_SG1__Sekkari_();}}
window.addEventListener('load',function(){var countIds=laavor_SG1__Furlings_.length;for(var iId=0;iId<countIds;iId++)
{laavor_SG1__Goa_uld_(iId,laavor_SG1__Furlings_[iId]);}});function laavor_SG1__Goa_uld_(_il_jdvc,ol_77_p_7){var pp__ilu_ww=document.getElementById(laavor_SG1__Furlings_[_il_jdvc]);laavor_SG1__Energy_beings_[ol_77_p_7]=[];if(pp__ilu_ww!==undefined&&pp__ilu_ww!==null){var laavor_SG1__Nakai_=pp__ilu_ww.children;var laavor_SG1__Tau_ri_=laavor_SG1__Nakai_.length;laavor_SG1__Ori_(laavor_SG1__Gadmeer_[ol_77_p_7]);try{for(var laavor_SG1__Nox_=0;laavor_SG1__Nox_<laavor_SG1__Tau_ri_;laavor_SG1__Nox_+=2){var heightContent=laa_vor_SG1__Dakara_(laavor_SG1__Nakai_[laavor_SG1__Nox_+1]);var laavor_SG1__Hybrids_={laavor_SG1__Jaffa_:laavor_SG1__Nakai_[laavor_SG1__Nox_],laavor_SG1__Kull_Warriors_:laavor_SG1__Nakai_[laavor_SG1__Nox_+1],HeightContent:heightContent};laavor_SG1__Nakai_[laavor_SG1__Nox_+1].style.display='none';laavor_SG1__Energy_beings_[ol_77_p_7].push(laavor_SG1__Hybrids_);var laavor_SG1__Ohne_=laavor_SG1__Serrakin_(laavor_SG1__Energy_beings_[ol_77_p_7].length-1);laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.setAttribute("LaavorAtrHex",laavor_SG1__Ohne_);laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.onclick=laavor_SG1__Stragoth_;laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.setAttribute("laavor_SG1__Alliance_of_four_great_races_",false);laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.setAttribute("__0_41_1",ol_77_p_7);laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.style.backgroundColor=laavor_SG1__Gadmeer_[ol_77_p_7].backgroundColorTitle;laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.style.border="solid 1px";laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.style.borderColor=laavor_SG1__Gadmeer_[ol_77_p_7].borderColorTitle;laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.style.color=laavor_SG1__Gadmeer_[ol_77_p_7].textColorTitle;laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.style.fontSize=laavor_SG1__Gadmeer_[ol_77_p_7].fontSizeTitle.replace("em","")+'em';laavor_SG1__Hybrids_.laavor_SG1__Kull_Warriors_.style.border="solid 1px";laavor_SG1__Hybrids_.laavor_SG1__Kull_Warriors_.style.borderColor=laavor_SG1__Gadmeer_.borderColorContent;laavor_SG1__Hybrids_.laavor_SG1__Kull_Warriors_.style.cursor="pointer";laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.style.marginBottom="0px";laavor_SG1__Hybrids_.laavor_SG1__Kull_Warriors_.style.marginBottom="0px";laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.style.marginTop="0px";laavor_SG1__Hybrids_.laavor_SG1__Kull_Warriors_.style.marginTop="0x";laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.onmouseover=laavor_SG1__Reol_;laavor_SG1__Hybrids_.laavor_SG1__Jaffa_.onmouseleave=laavor_SG1__Replicators_;}
if(laavor_SG1__Gadmeer_[ol_77_p_7].toString()==="true"){laavor_SG1__Energy_beings_[0].laavor_SG1__Jaffa_.setAttribute("laavor_SG1__Alliance_of_four_great_races_",true);laa_vor_SG1__Athosians_(laavor_SG1__Energy_beings_[0]);laavor_SG1__Dust_Bugs_[ol_77_p_7]=laavor_SG1__Energy_beings_[0];}
else{laavor_SG1__Dust_Bugs_[ol_77_p_7]=null;}}
catch(e){throw new Error("The Title and Content order can not be interrupted, if necessary contact Laavor support.");}}
else{throw new Error("Item with idFather informed was not found.");}}
function laavor_SG1__Reol_(){if(this!==undefined&&this!==null){var ilj_745_=this.getAttribute("__0_41_1");if(ilj_745_!==undefined&&ilj_745_!==null)
{this.style.backgroundColor=laavor_SG1__Gadmeer_[ilj_745_].backgroundColorTitleHover;this.style.borderColor=laavor_SG1__Gadmeer_[ilj_745_].borderColorTitleHover;this.style.color=laavor_SG1__Gadmeer_[ilj_745_].textColorTitleHover;}}}
function laavor_SG1__Replicators_(){if(this!==undefined&&this!==null){var _ialaoal_=this.getAttribute("laavor_SG1__Alliance_of_four_great_races_");var _hj_aas_d=this.getAttribute("__0_41_1");if(_ialaoal_==="false"){this.style.backgroundColor=laavor_SG1__Gadmeer_[_hj_aas_d].backgroundColorTitle;this.style.borderColor=laavor_SG1__Gadmeer_[_hj_aas_d].borderColorTitle;this.style.color=laavor_SG1__Gadmeer_[_hj_aas_d].textColorTitle;}
else{this.style.backgroundColor=laavor_SG1__Gadmeer_[_hj_aas_d].backgroundColorTitleSelected;this.style.borderColor=laavor_SG1__Gadmeer_[_hj_aas_d].borderColorTitleSelected;this.style.color=laavor_SG1__Gadmeer_[_hj_aas_d].textColorTitleSelected;}}}
function laavor_SG1__Ori_(laavor_SG1__Re_tu_){var afavafavarr____=laavor_SG1__Sekkari_();if(laavor_SG1__Re_tu_.viewMode===undefined||laavor_SG1__Re_tu_.viewMode===null){laavor_SG1__Re_tu_.viewMode=afavafavarr____.viewMode;}
if(laavor_SG1__Re_tu_.preSelectItem===undefined||laavor_SG1__Re_tu_.preSelectItem===null){laavor_SG1__Re_tu_.preSelectItem=afavafavarr____.preSelectItem;}
if(laavor_SG1__Re_tu_.backgroundColorTitle===undefined||laavor_SG1__Re_tu_.backgroundColorTitle===null){laavor_SG1__Re_tu_.backgroundColorTitle=afavafavarr____.backgroundColorTitle;}
if(laavor_SG1__Re_tu_.backgroundColorTitleHover===undefined||laavor_SG1__Re_tu_.backgroundColorTitleHover===null){laavor_SG1__Re_tu_.backgroundColorTitleHover=afavafavarr____.backgroundColorTitleHover;}
if(laavor_SG1__Re_tu_.borderColorTitle===undefined||laavor_SG1__Re_tu_.borderColorTitle===null){laavor_SG1__Re_tu_.borderColorTitle=afavafavarr____.borderColorTitle;}
if(laavor_SG1__Re_tu_.borderColorTitleHover===undefined||laavor_SG1__Re_tu_.borderColorTitleHover===null){laavor_SG1__Re_tu_.borderColorTitleHover=afavafavarr____.borderColorTitleHover;}
if(laavor_SG1__Re_tu_.textColorTitle===undefined||laavor_SG1__Re_tu_.textColorTitle===null){laavor_SG1__Re_tu_.textColorTitle=afavafavarr____.textColorTitle;}
if(laavor_SG1__Re_tu_.textColorTitleHover===undefined||laavor_SG1__Re_tu_.textColorTitleHover===null){laavor_SG1__Re_tu_.textColorTitleHover=afavafavarr____.textColorTitleHover;}
if(laavor_SG1__Re_tu_.borderSizeTitle===undefined||laavor_SG1__Re_tu_.borderSizeTitle===null){laavor_SG1__Re_tu_.borderSizeTitle=afavafavarr____.borderSizeTitle;}
if(laavor_SG1__Re_tu_.borderTitleHasShadow===undefined||laavor_SG1__Re_tu_.borderTitleHasShadow===null){laavor_SG1__Re_tu_.borderTitleHasShadow=afavafavarr____.borderTitleHasShadow;}
if(laavor_SG1__Re_tu_.borderContentHasShadow===undefined||laavor_SG1__Re_tu_.borderContentHasShadow===null){laavor_SG1__Re_tu_.borderContentHasShadow=afavafavarr____.borderContentHasShadow;}
if(laavor_SG1__Re_tu_.fontSizeTitle===undefined||laavor_SG1__Re_tu_.fontSizeTitle===null){laavor_SG1__Re_tu_.fontSizeTitle=afavafavarr____.fontSizeTitle;}
if(laavor_SG1__Re_tu_.borderColorContent===undefined||laavor_SG1__Re_tu_.borderColorContent===null){laavor_SG1__Re_tu_.borderColorContent=afavafavarr____.borderColorContent;}
if(laavor_SG1__Re_tu_.backgroundColorTitleSelected===undefined||laavor_SG1__Re_tu_.backgroundColorTitleSelected===null){laavor_SG1__Re_tu_.backgroundColorTitleSelected=afavafavarr____.backgroundColorTitleSelected;}
if(laavor_SG1__Re_tu_.textColorTitleSelected===undefined||laavor_SG1__Re_tu_.textColorTitleSelected===null){laavor_SG1__Re_tu_.textColorTitleSelected=afavafavarr____.textColorTitleSelected;}
if(laavor_SG1__Re_tu_.borderColorTitleSelected===undefined||laavor_SG1__Re_tu_.borderColorTitleSelected===null){laavor_SG1__Re_tu_.borderColorTitleSelected=afavafavarr____.borderColorTitleSelected;}}
function laavor_SG1__Serrakin_(jahjsahjkasjkhSAJKHsajkh){"use strict";var laavor_SG1__Shadow_entity_="";var laavor_SG1__Spirits_="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";for(var blabla=0;blabla<15;blabla++){laavor_SG1__Shadow_entity_+=laavor_SG1__Spirits_.charAt(Math.floor(Math.random()*laavor_SG1__Spirits_.length));}
laavor_SG1__Shadow_entity_+='_'+jahjsahjkasjkhSAJKHsajkh.toString();return laavor_SG1__Shadow_entity_;}
function laavor_SG1__Stragoth_(){try{var aer_azc_71=this.getAttribute("__0_41_1");var laavor_SG1__Unas_=this.getAttribute("LaavorAtrHex");var laavor_SG1__Wraith_=this.getAttribute("laavor_SG1__Alliance_of_four_great_races_");var laavor_SG1__Unity_=laavor_SG1__Unas_.split('_')[1].toString().res_is_42();var laavor_SG1__Ursini_=laavor_SG1__Energy_beings_[aer_azc_71][laavor_SG1__Unity_];var laavor_SG1__Water_lifeform_=false;if(laavor_SG1__Ursini_!==undefined&&laavor_SG1__Ursini_!==null){if(laavor_SG1__Gadmeer_[aer_azc_71].viewMode!==undefined&&laavor_SG1__Gadmeer_[aer_azc_71].viewMode!==null){if(laavor_SG1__Wraith_.toString()==='true'){laa_vor_SG1__Tok_ra_(laavor_SG1__Ursini_);laavor_SG1__Water_lifeform_=true;}else{laa_vor_SG1__Athosians_(laavor_SG1__Ursini_);}
if(laavor_SG1__Gadmeer_[aer_azc_71].viewMode==='single'){if(laavor_SG1__Dust_Bugs_[aer_azc_71]!==undefined&&laavor_SG1__Dust_Bugs_[aer_azc_71]!==null){var laa_vor_SG1__Genii_=this.getAttribute("LaavorAtrHex");var laa_vor_SG1__Satedans_=laavor_SG1__Dust_Bugs_[aer_azc_71].laavor_SG1__Jaffa_.getAttribute("LaavorAtrHex");if(laa_vor_SG1__Genii_!==laa_vor_SG1__Satedans_){laa_vor_SG1__Tok_ra_(laavor_SG1__Dust_Bugs_[aer_azc_71]);}}}}else if(laavor_SG1__Dust_Bugs_!==undefined&&laavor_SG1__Dust_Bugs_!==null){laa_vor_SG1__Tok_ra_(laavor_SG1__Dust_Bugs_[aer_azc_71]);}
laavor_SG1__Dust_Bugs_[aer_azc_71]=laavor_SG1__Ursini_;}else{throw new Error("Error in count inside Accordion(Click Item) contact Laavor.com with example.");}}catch(e){throw new Error("Error in count inside Accordion(Click Item) contact Laavor.com with example.");}}
function laa_vor_SG1__Dakara_(laa_vor_SG1__Travelers_){if(laa_vor_SG1__Travelers_.clientHeight!==undefined&&laa_vor_SG1__Travelers_.clientHeight!==null){return laa_vor_SG1__Travelers_.clientHeight.toString().res_is_42();}
if(laa_vor_SG1__Travelers_.height!==undefined&&laa_vor_SG1__Travelers_.style.height!==null){return laa_vor_SG1__Travelers_.height.toString().res_is_42();}
if(laa_vor_SG1__Travelers_.offsetHeight!==undefined&&laa_vor_SG1__Travelers_.offsetHeight!==null){return laa_vor_SG1__Travelers_.offsetHeight.toString().res_is_42()-2;}else{throw new Error("Error in count inside Accordion(Height Item) contact Laavor.com with example.");}}
function laa_vor_SG1__Pegasus_(laa_vor_SG1__Atlantis_,_laavor_Tom_and_Jerry,time){setTimeout(function(){laa_vor_SG1__Atlantis_.style.height=_laavor_Tom_and_Jerry.toString().replace("px","")+'px';},time);}
function laa_vor_SG1__Tok_ra_(laa_vor_SG1__Ascension){if(laa_vor_SG1__Ascension.laavor_SG1__Kull_Warriors_!==undefined&&laa_vor_SG1__Ascension.laavor_SG1__Kull_Warriors_!==null&&laa_vor_SG1__Ascension.HeightContent!==undefined&&laa_vor_SG1__Ascension.HeightContent!==null){var laa_vor_SG1__The_Yogi_Bear_Show_=laa_vor_SG1__Ascension.HeightContent/10;var laa_vor_SG1__Wacky_Races_=0;var laa_vor_SG1__The_Smurfs_=50;laa_vor_SG1__Ascension.laavor_SG1__Kull_Warriors_.style.opacity="0";for(var iStepA=laa_vor_SG1__Ascension.HeightContent;iStepA>0;iStepA-=laa_vor_SG1__The_Yogi_Bear_Show_){laa_vor_SG1__Pegasus_(laa_vor_SG1__Ascension.laavor_SG1__Kull_Warriors_,iStepA,laa_vor_SG1__The_Smurfs_);if(laa_vor_SG1__Wacky_Races_>11){throw new Error("Error in count inside Accordion(Hide Item) contact Laavor.com with example.");}
laa_vor_SG1__The_Smurfs_+=50;}
setTimeout(function(){laa_vor_SG1__Ascension.laavor_SG1__Kull_Warriors_.style.height='0px';},laa_vor_SG1__The_Smurfs_);laa_vor_SG1__The_Smurfs_+=50;setTimeout(function(){laa_vor_SG1__Ascension.laavor_SG1__Kull_Warriors_.style.display='none';},laa_vor_SG1__The_Smurfs_);laa_vor_SG1__The_Smurfs_+=50;setTimeout(function(){var bb_v_11_=laa_vor_SG1__Ascension.laavor_SG1__Jaffa_.getAttribute("__0_41_1");laa_vor_SG1__Ascension.laavor_SG1__Kull_Warriors_.style.height=laa_vor_SG1__Ascension.HeightContent.toString()+'px';laa_vor_SG1__Ascension.laavor_SG1__Jaffa_.style.backgroundColor=laavor_SG1__Gadmeer_[bb_v_11_].backgroundColorTitle;laa_vor_SG1__Ascension.laavor_SG1__Jaffa_.style.color=laavor_SG1__Gadmeer_[bb_v_11_].textColorTitle;laa_vor_SG1__Ascension.laavor_SG1__Jaffa_.style.borderColor=laavor_SG1__Gadmeer_[bb_v_11_].borderColorTitle;},laa_vor_SG1__The_Smurfs_);laa_vor_SG1__Ascension.laavor_SG1__Jaffa_.setAttribute("laavor_SG1__Alliance_of_four_great_races_",false);}}
function laa_vor_SG1__Athosians_(laa_vor_SG1__The_Flintstones_){if(laa_vor_SG1__The_Flintstones_.laavor_SG1__Kull_Warriors_!==undefined&&laa_vor_SG1__The_Flintstones_.laavor_SG1__Kull_Warriors_!==null&&laa_vor_SG1__The_Flintstones_.HeightContent!==undefined&&laa_vor_SG1__The_Flintstones_.HeightContent!==null){var laa_vor_SG1__The_Jetsons_=laa_vor_SG1__The_Flintstones_.HeightContent/10;var laa_vor_SG1__Scooby_Doo_=0;var laa_vor_SG1__Super_Friends_=50;laa_vor_SG1__The_Flintstones_.laavor_SG1__Kull_Warriors_.style.height=laa_vor_SG1__The_Jetsons_.toString()+'px';laa_vor_SG1__The_Flintstones_.laavor_SG1__Kull_Warriors_.style.display='block';for(var iStepA=laa_vor_SG1__The_Jetsons_;iStepA<=laa_vor_SG1__The_Flintstones_.HeightContent;iStepA+=laa_vor_SG1__The_Jetsons_){laa_vor_SG1__Pegasus_(laa_vor_SG1__The_Flintstones_.laavor_SG1__Kull_Warriors_,iStepA,laa_vor_SG1__Super_Friends_);if(laa_vor_SG1__Scooby_Doo_>11){throw new Error("Error in count inside Accordion(Hide Item) contact Laavor.com with example.");}
laa_vor_SG1__Super_Friends_+=50;}
setTimeout(function(){var bb_v_77_=laa_vor_SG1__The_Flintstones_.laavor_SG1__Jaffa_.getAttribute("__0_41_1");laa_vor_SG1__The_Flintstones_.laavor_SG1__Kull_Warriors_.style.height=laa_vor_SG1__The_Flintstones_.HeightContent.toString()+'px';laa_vor_SG1__The_Flintstones_.laavor_SG1__Kull_Warriors_.style.opacity="1";laa_vor_SG1__The_Flintstones_.laavor_SG1__Jaffa_.style.backgroundColor=laavor_SG1__Gadmeer_[bb_v_77_].backgroundColorTitleSelected;laa_vor_SG1__The_Flintstones_.laavor_SG1__Jaffa_.style.color=laavor_SG1__Gadmeer_[bb_v_77_].textColorTitleSelected;laa_vor_SG1__The_Flintstones_.laavor_SG1__Jaffa_.style.borderColor=laavor_SG1__Gadmeer_[bb_v_77_].borderColorTitleSelected;},laa_vor_SG1__Super_Friends_);laa_vor_SG1__Super_Friends_+=50;laa_vor_SG1__The_Flintstones_.laavor_SG1__Jaffa_.setAttribute("laavor_SG1__Alliance_of_four_great_races_",true);}}
function laavor_SG1__Sekkari_(){return{viewMode:'single',preSelectItem:true,backgroundColorTitle:"orange",borderColorTitle:"black",borderSizeTitle:"8px",textColorTitle:"black",fontSizeTitle:"2em",backgroundColorTitleHover:"gray",borderColorTitleHover:"black",textColorTitleHover:"white",borderTitleHasShadow:true,borderColorContent:"black",backgroundColorTitleSelected:"#f0f0f0",textColorTitleSelected:"black",borderColorTitleSelected:"white"};}